### ISSUE TITLE
Linux Extension Not Loading

### ISSUE THREAD

**Issue by Riotline** [sigsegv-mvm/TFMaxVoiceSpeakDelayUnlimiter#1]
The Linux extension cannot load cus it says 

CXXABI_1.3.9 not found

**Comment by sigsegv-mvm** [comment]
I've recompiled and pushed a [new release](https://github.com/sigsegv-mvm/TFMaxVoiceSpeakDelayUnlimiter/releases/tag/20180402-1) for Linux that should fix this problem.

I think Valve recently changed something about the version of `libstdc++.so.6` that they distribute (either with Steam or with TF2), which may have involved changing it to an older version... or something. Not entirely sure. In any case, the new build should now be compatible with older C++ standard library versions.

Let me know if anything further comes up regarding this.
